### ISSUE TITLE
비동기 데이터 IO 처리

### ISSUE THREAD

**Issue by Jeong-Rae** [KeepYourCost/StreamAgent#4]
# Title
비동기 데이터 IO 처리

# Description
현재 Write 작업은 동기적으로 Consume 한 데이터를 읽어 처리하고 있음
이에 Write 호출 자체는 순서를 지키게 되어 있음
사전에 index 크기를 미리 읽을 수 있으면, 빈 chunk 채우기 방식을 통한 병렬 연산 진행이 가능함

# Task
- [ ] 인덱스 정보 제공 방법 고민
- [ ] 동기, 비동기 성능 비교 테스트
- [ ] 병렬 연산 도입
